theme: jekyll-theme-cayman
title: "ES6 Harmony"
description: "ES6 equivalent implimentation in ES5 for old JavaScript engines"
show_downloads: "true"
google_analytics: "UA-114357378-1"
theme_color: "#061166"
github:
  zip_url: "https://github.com/rousan/es6-harmony/zipball/master"
  tar_url: "https://github.com/rousan/es6-harmony/tarball/master"
